Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root to: 'pages#home'
  get 'index', to: 'pages#index'
  get 'drumkit', to: 'pages#drumkit'
  get 'clock', to: 'pages#clock'
  get 'variables', to: 'pages#variables'
  get 'gallery', to: 'pages#gallery'
  get 'ajax', to: 'pages#ajax'
  get 'canvas', to: 'pages#canvas'
  get 'checkboxes', to: 'pages#checkboxes'
  get 'video', to: 'pages#video'
  get 'delegation', to: 'pages#delegation'
  get 'sequence', to: 'pages#sequence'
  get 'scroll', to: 'pages#scroll'
  get 'mouse', to: 'pages#mouse'
  get 'sorting', to: 'pages#sorting'
  get 'reduce', to: 'pages#reduce'
  get 'webcam', to: 'pages#webcam'
  get 'speech', to: 'pages#speech'
  get 'speedometer', to: 'pages#speedometer'
  get 'followlinks', to: 'pages#followlinks'
  
  get 'speechsynthesis', to: 'pages#speechsynthesis'
  get 'stickynav', to: 'pages#stickynav'
  get 'bubbling', to: 'pages#bubbling'
  get 'stripedropdown', to: 'pages#stripedropdown'
  get 'clickanddrag', to: 'pages#clickanddrag'
  get 'videospeed', to: 'pages#videospeed'
  get 'countdown', to: 'pages#countdown'
  get 'whackamole', to: 'pages#whackamole'

end
